
@startuml

[*] -> Importer
Importer -> Preprocessor
Preprocessor : - lowercase
Preprocessor : - html removal
Preprocessor : - url removal
Preprocessor : - stem
Preprocessor : - stop-word removal
Preprocessor : - domain term removal
Preprocessor : - punctuation removal
Preprocessor : - number removal
Preprocessor : - bigram removal
Preprocessor : - high/low frequency term removal

Preprocessor -> Topics_K

Topics_K -> LDA_DE
LDA_DE: - find best alpha and beta
LDA_DE -> [*]


@enduml